spring:
  kafka:
    bootstrap-servers: localhost:9092
  config:
    import: optional:configserver:http://localhost:8085
  application:
    name: stgateway
management:
  endpoints:
    web:
      exposure:
        include: busrefresh,refresh,health,info
app:
  message: this is gateway server